### ISSUE TITLE
Archetype Overrides function not working

### ISSUE THREAD

**Issue by jasperpostcn** [Azure/Azure-Landing-Zones-Library#185]
According to [this](https://azure.github.io/Azure-Landing-Zones-Library/assets/archetype-overrides/) documentation I should be able to remove specific policy assignments or role_definitions from specific archetypes. 

As an example, on the root archetype one of the policy assignments is called `Deploy-MDFC-OssDb`. When creating file `root.alz_archetype_override.yaml` with the following content:

```
---
name: root_override
base_archetype: root
policy_assignments_to_add: []
policy_assignments_to_remove:
  - "Deploy-MDFC-OssDb"
policy_definitions_to_add: []
policy_definitions_to_remove:
policy_set_definitions_to_add: []
policy_set_definitions_to_remove: []
role_definitions_to_add: []
role_definitions_to_remove: []
```

This is my `alz.alz_architecture_definition.yaml` file, with only 2 managent groups / archetypes:
```
---
name: alz
management_groups:
- archetypes:
  - root
  display_name: ALZ
  exists: false
  id: mg_alz
  parent_id: null
- archetypes:
  - platform
  display_name: Platform
  exists: false
  id: mg_platform
  parent_id: mg_alz
```

It doesn't change anything. I am using version `2025.02.0` and have the `library_overwrite_enabled` set to `true`.

**Comment by mattoddie** [comment]
@jasperpostcn this took me a while to figure out too as not particularly well documented, but you need to change the archetype in your architecture definition to the name of the override e.g.

```yaml
---
name: alz
management_groups:
- archetypes:
  - root_override
  display_name: ALZ
  exists: false
  id: mg_alz
  parent_id: null
- archetypes:
  - platform
  display_name: Platform
  exists: false
  id: mg_platform
  parent_id: mg_alz
```
